### ISSUE TITLE
[IDEA] Засады

### ISSUE THREAD

**Issue by lemshake** [Fallout-13-ru/F13StashOfAtom#1]
#### Идея: 
Система засад. Определенный тип симплмобов при определенных факторах (Звуки выстрелов, крики) будет спавниться вне поля зрения игрока и нападать на него.
При отсутствии цели, эти симплмобы будут деспавниться чтобы не засорять мир.

#### Что по вашему мнению это принесет в билд:
На данный момент, почти всегда за 20 минут с начала раунда, вся основная карта зачищается и становится полностью безопасной. Засады, вызванные шумностью игроков агрессивные мутанты будут компенсировать это и делать пустошь опасной, какой она и должна быть всегда.

**Comment by lemshake** [comment]
Я это сам буду кодить, но хочу узнать мнение остальных.
Изменено: Я больше не кодер

**Comment by Waklaidan** [comment]
Предлагаю сделать заместо этого система респавна мобов в зависимости от онлайна.
Потому что такая система ещё больше нагрузит билд ИИ мобов, которых и так уже 900 на карте

**Comment by Waklaidan** [comment]
ну или дать мне просто баунти, тогда я сделаю

**Comment by Waklaidan** [comment]
вебхук

**Comment by Waklaidan** [comment]
вебхрюк

**Comment by lemshake** [comment]
УУУХ бабки отработаны

**Comment by lemshake** [comment]
(я больше не кодер)
